force-app/main/default/objects/Web_User__c/Web_User__c.object-meta.xml
<CustomObject>
    <description>Storing the web user coming from the external system</description>
    <label>Web User</label>
    <nameField>
        <label>Web User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web User Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_User__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Company to which the user belongs</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email in the external system</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Web_User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username from the external system</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Web_User__c/fields/Web_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Web_Site_Id__c</fullName>
    <description>External Id between Salesforce and the external sytem</description>
    <label>Web Site Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestUsersDataFactory.cls
@isTest
public class TestUsersDataFactory {
    public static void createWebUser( String CompanyName) {
        Web_User__c webUser = new Web_User__c();
        webUser.Name='Test1';
        webUser.UserName__c='test1@test.user.ks';
        webUser.Email__c='Test1@test.user.ks';
        webUser.Name='Test1';
        webUser.Company__c = CompanyName;
        webUser.Web_Site_Id__c ='test.sk.com';
        insert webUser;
    }
    
    public static void createDuplicateWebUser(String CompanyName) {
        Web_User__c webUser = new Web_User__c();
        webUser.Name='Test2';
        webUser.UserName__c='test2@test.user.ks';
        webUser.Email__c='Test2@test.user.ks';
        webUser.Name='Test2';
        webUser.Company__c = CompanyName;
        webUser.Web_Site_Id__c ='test.sk.com';
        insert webUser;
    }
}