force-app/main/default/objects/Web_User__c/Web_User__c.object-meta.xml
<CustomObject>
    <description>Storing the web user coming from the external system</description>
    <label>Web User</label>
    <nameField>
        <label>Web User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web User Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_User__c/fields/IsPremium__c.field-meta.xml
<CustomField>
    <fullName>IsPremium__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPremium</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Web_User__c/fields/Web_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Web_Site_Id__c</fullName>
    <description>External Id between Salesforce and the external sytem</description>
    <label>Web Site Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebUserTriggerTest.cls
@isTest
public class WebUserTriggerTest {
    
    @isTest
    public static Void WebUserTriggerDuplicateCheck()
    {
        Boolean expectedError = false;   
        try{
            Test.startTest();
            TestUsersDataFactory.createWebUser('Johns Group');
            TestUsersDataFactory.createDuplicateWebUser('Johns Group');
            Test.stopTest();
        }catch(DmlException dmlExc){ 
            expectedError =  dmlExc.getMessage().contains('There is already user with same Web Site Id') ? true : false;
        }
        System.assertEquals(expectedError, true);
    }
    
    @isTest
    public static Void WebUserTriggerIsPremiumTrue() {
        try{
            Test.startTest();
            TestUsersDataFactory.createWebUser('Johns Group');
            Web_User__c webUser = [SELECT Id, IsPremium__c FROM Web_User__c WHERE Web_Site_Id__c ='test.sk.com' LIMIT 1];
            Test.stopTest();
            System.assertEquals(webUser.IsPremium__c, true);
        }catch(Exception exc){ 
            System.debug('Error Message :' + exc.getMessage());
        }
    }
    
    @isTest
    public static Void WebUserTriggerIsPremiumFalse() {
        try{
            Test.startTest();
            TestUsersDataFactory.createWebUser('Zopa');
            Web_User__c webUser = [SELECT Id, IsPremium__c FROM Web_User__c WHERE Web_Site_Id__c ='test.sk.com' LIMIT 1];
            Test.stopTest();
            System.assertEquals(webUser.IsPremium__c, false);
        }catch(Exception exc){ 
            System.debug('Error Message :' + exc.getMessage());
        }
    }
}